server:
  port: 80
spring:
  data:
    redis:
      database: 3 #3號數據庫，可自行更改
      host: localhost
      port: 6379
      jedis: #可設可不設
        pool:
          max-active: 100 #最大連接數
          max-idle: 100 #最大空閒連接數，通常和最大連接數相等
          min-idle: 10 #初始連接數
          max-wait: 1000ms #等待連結時長，超過則逾時
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/f3469?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 850117
  freemarker:
    suffix: .ftl
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #底線自動轉換為小駝峰